grasp_selection_node:
  ros__parameters:
    input_topic: "grasp_candidates"
    output_topic: "selected_grasp"
    
    # Options: highest_score, top_down, nearest_depth, top_k_aligned, ergonomic
    policy: "ergonomic"
    
    top_down_max_tilt_deg: 30.0
    top_down_strict: false
    
    # defaults to camera frame
    output_frame: "camera_color_optical_corrected"

handover_orchestrator:
  ros__parameters:
    selected_grasp_topic: "selected_grasp"
    capture_trigger_topic: "capture_trigger"
    hand_status_topic: "hand_stability_status"
    system_state_topic: "system_state"
    
    # 'auto' (hand stability) or 'manual' (Enter key)
    trigger_mode: "manual"
    hand_wait_timeout_sec: 30.0
    
    capture_timeout_sec: 15.0
    
    planning_group: "panda_arm"
    planning_frame: "panda_link0"
    ee_link: "panda_hand"
    
    max_velocity_scaling: 0.2
    max_acceleration_scaling: 0.1
    planning_time: 5.0

    # Requires orchestrator terminal
    confirm_before_execute: false

    gripper_open_width: 0.08
    gripper_open_speed: 0.1
    grasp_width: 0.0
    grasp_speed: 0.03
    grasp_force: 40.0
    grasp_epsilon_inner: 0.1
    grasp_epsilon_outer: 0.1

    home_joints:
      - 0.02339568794756837
      - -0.32465551723001435
      - -0.032348319990882765
      - -2.5288589074640533
      - 0.009927281832031128
      - 2.293500571313975
      - 0.7461003649698391

    dropoff_joints:
      - 0.0761
      - 0.0087
      - 0.0108
      - -2.7316
      - -0.0448
      - 2.7889
      - 0.8629

    hand_tcp_offset: 0.1034
    pregrasp_distance: 0.10

    min_grasp_z: 0.0

    grasp_offset_tcp: [0.035, -0.09, 0.03]

    # Orient downwards regardless of prediction
    force_top_down_grasp: false

    table_enable: false
    table_position: [0.4, 0.0, -0.1]
    table_size: [1.2, 1.2, 0.05]

    release_detection_mode: "timeout"
    release_timeout_sec: 3.0
